name: Develop CI/CD
on: 
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  develop_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Setup
        run: npm ci

      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  
      - name: Build Angular, output in dist/mycv
        run: |
          CI=false npm run build
          
      - name: Show directory content
        run: |
          ls -la dist/mycv/browser

      - name: Download and run httpd image, container name serving_develop
        run: |
          docker run -d --name serving_develop httpd
          
      - name: List running Docker containers
        run: |
          docker ps
          
      - name: Copy Angular build to container
        run: |
          docker cp dist/mycv/browser/. serving_develop:/usr/local/apache2/htdocs

      - name: List container directory content
        run: |
          docker exec serving_develop ls -la /usr/local/apache2/htdocs
